### ISSUE TITLE
A clear violation of my rules!

### ISSUE THREAD

**Issue by Free-IPTV** [open-iptv/streams#1]
@rduetsch!

A clear violation of my rules! You didn't think it necessary to ask me beforehand!

If I catch you again misusing my m3u's or parts of them for others, you will be reported to Github for violating existing rules!

READ my readme! From my side there is ONLY ONE permit for a non-private use and it went to the Linux-Mint team!

https://github.com/Free-IPTV/Countries/blob/master/README.md

Not only me but a few others will now keep an eye on you, what you are doing!

Now come up with something very quickly, because you didn't ask me. Meditate with me then, by ISSUE!

**Comment by rduetsch** [comment]
Hello i am sorry i did not like to violate the rules sorry i just testing for myself i do like to colaborate with you where ever i can an if possibel..... i am just testing for myself a nice tool to make my own m3u playlist for mi sat recievers and streaming devices

**Comment by Free-IPTV** [comment]
If you want to test something for yourself privately, that's okay, but here your repo is for everyone, so it's public!

In your openiptvM3UPlaylist.m3u are complete parts of my M3u's were available. It's also easy to find what has been copied, especially the logos that I searched for and entered as an alternative logos for RK TV! Example: tvg-logo = "https://i.imgur.com/l3C0eDv.jpg" end etc. 

Read my Readme in my repo. Copy and paste, sharing of my m3u´s on public pages on the Internet is not permitted.

If you want to use something publicly, please ask me in advance before. It doesn't cost anything to ask.

**Comment by rduetsch** [comment]
sorry i wasn´t aware of my rookie mistake

**Comment by rduetsch** [comment]
i was playing a rround with this tool : https://m3u4u.com/ where i updated the logos i am sorry i just played arround and used your  m3u for my private playlist thank you for the source you make a big job i realy just used it for privat interest having open tv in all rooms

**Comment by rduetsch** [comment]
tell me how i can contribute with you if possible

**Comment by Free-IPTV** [comment]
Hi,

look to the Pull-requests in my repo, there you can see, how you can contribute.

https://github.com/Free-IPTV/Countries/pulls?q=is%3Apr+is%3Aclosed

For the rules read the readme. ;-) If you want to contribute me, you create an fork, edit files in your forl and then make a pull-request.

**Comment by rduetsch** [comment]
ok thank you and sorry for the caused violation
